# -*- coding: utf-8 -*-
"""Typings and the type effectiveness chart, CURRENT (Gen 6+) rules.

Deliberately not the Gen 1 chart, even though the rest of the game is Gen 1
flavoured. Three reasons: the Gen 1 chart shipped real bugs (Ghost moves did
nothing at all to Psychic), Psychic was resisted only by Psychic and so ran
away with every battle, and -- decisively -- the base stats in dex_stats.py
were already pulled from PokeAPI at their CURRENT values, not their Gen 1 ones
(Pidgeot has 101 Speed here, not the 91 it had in Red/Blue). Modern stats with
an ancient chart is the inconsistent combination; this makes the data cohere.

Fairy also earns its place: Dragonite has the highest Attack in the dex, and
under pre-Gen-6 rules Dragon is resisted only by Steel. Dragon -> Fairy is 0x,
which hands the player a real answer to the strongest thing they can hatch.

Consumed by gen_dex.py, which emits dex.h.
"""

# Order matters: it is the index order of the effectiveness matrix and of the
# PkType enum in dex.h.
TYPE_ORDER = [
    'normal', 'fire', 'water', 'electric', 'grass', 'ice', 'fighting',
    'poison', 'ground', 'flying', 'psychic', 'bug', 'rock', 'ghost',
    'dragon', 'dark', 'steel', 'fairy',
]

# Attacker -> {defender: multiplier}. Anything unlisted is 1x.
# Current (Gen 6+) chart. Note Steel lost its Dark and Ghost resistances in
# Gen 6, so those cells are neutral here and not 0.5x.
CHART = {
    'normal':   {'rock': .5, 'ghost': 0, 'steel': .5},
    'fire':     {'fire': .5, 'water': .5, 'grass': 2, 'ice': 2, 'bug': 2,
                 'rock': .5, 'dragon': .5, 'steel': 2},
    'water':    {'fire': 2, 'water': .5, 'grass': .5, 'ground': 2, 'rock': 2,
                 'dragon': .5},
    'electric': {'water': 2, 'electric': .5, 'grass': .5, 'ground': 0,
                 'flying': 2, 'dragon': .5},
    'grass':    {'fire': .5, 'water': 2, 'grass': .5, 'poison': .5, 'ground': 2,
                 'flying': .5, 'bug': .5, 'rock': 2, 'dragon': .5, 'steel': .5},
    'ice':      {'fire': .5, 'water': .5, 'grass': 2, 'ice': .5, 'ground': 2,
                 'flying': 2, 'dragon': 2, 'steel': .5},
    'fighting': {'normal': 2, 'ice': 2, 'poison': .5, 'flying': .5,
                 'psychic': .5, 'bug': .5, 'rock': 2, 'ghost': 0, 'dark': 2,
                 'steel': 2, 'fairy': .5},
    'poison':   {'grass': 2, 'poison': .5, 'ground': .5, 'rock': .5,
                 'ghost': .5, 'steel': 0, 'fairy': 2},
    'ground':   {'fire': 2, 'electric': 2, 'grass': .5, 'poison': 2,
                 'flying': 0, 'bug': .5, 'rock': 2, 'steel': 2},
    'flying':   {'electric': .5, 'grass': 2, 'fighting': 2, 'bug': 2,
                 'rock': .5, 'steel': .5},
    'psychic':  {'fighting': 2, 'poison': 2, 'psychic': .5, 'dark': 0,
                 'steel': .5},
    'bug':      {'fire': .5, 'grass': 2, 'fighting': .5, 'poison': .5,
                 'flying': .5, 'psychic': 2, 'ghost': .5, 'dark': 2,
                 'steel': .5, 'fairy': .5},
    'rock':     {'fire': 2, 'ice': 2, 'fighting': .5, 'ground': .5,
                 'flying': 2, 'bug': 2, 'steel': .5},
    'ghost':    {'normal': 0, 'psychic': 2, 'ghost': 2, 'dark': .5},
    'dragon':   {'dragon': 2, 'steel': .5, 'fairy': 0},
    'dark':     {'fighting': .5, 'psychic': 2, 'ghost': 2, 'dark': .5,
                 'fairy': .5},
    'steel':    {'fire': .5, 'water': .5, 'electric': .5, 'ice': 2, 'rock': 2,
                 'steel': .5, 'fairy': 2},
    'fairy':    {'fire': .5, 'fighting': 2, 'poison': .5, 'dragon': 2,
                 'dark': 2, 'steel': .5},
}

# Typing of the 151 under current (Gen 6+) rules. Seven differ from Gen 1:
# Magnemite/Magneton gained Steel in Gen 2, and Clefairy, Clefable, Jigglypuff,
# Wigglytuff and Mr. Mime gained Fairy in Gen 6 (the first two becoming PURE
# Fairy, losing Normal entirely).
TYPES = {
    1: ('grass', 'poison'), 2: ('grass', 'poison'), 3: ('grass', 'poison'),
    4: ('fire', None), 5: ('fire', None), 6: ('fire', 'flying'),
    7: ('water', None), 8: ('water', None), 9: ('water', None),
    10: ('bug', None), 11: ('bug', None), 12: ('bug', 'flying'),
    13: ('bug', 'poison'), 14: ('bug', 'poison'), 15: ('bug', 'poison'),
    16: ('normal', 'flying'), 17: ('normal', 'flying'), 18: ('normal', 'flying'),
    19: ('normal', None), 20: ('normal', None),
    21: ('normal', 'flying'), 22: ('normal', 'flying'),
    23: ('poison', None), 24: ('poison', None),
    25: ('electric', None), 26: ('electric', None),
    27: ('ground', None), 28: ('ground', None),
    29: ('poison', None), 30: ('poison', None), 31: ('poison', 'ground'),
    32: ('poison', None), 33: ('poison', None), 34: ('poison', 'ground'),
    35: ('fairy', None), 36: ('fairy', None),  # pure Fairy from Gen 6
    37: ('fire', None), 38: ('fire', None),
    39: ('normal', 'fairy'), 40: ('normal', 'fairy'),
    41: ('poison', 'flying'), 42: ('poison', 'flying'),
    43: ('grass', 'poison'), 44: ('grass', 'poison'), 45: ('grass', 'poison'),
    46: ('bug', 'grass'), 47: ('bug', 'grass'),
    48: ('bug', 'poison'), 49: ('bug', 'poison'),
    50: ('ground', None), 51: ('ground', None),
    52: ('normal', None), 53: ('normal', None),
    54: ('water', None), 55: ('water', None),
    56: ('fighting', None), 57: ('fighting', None),
    58: ('fire', None), 59: ('fire', None),
    60: ('water', None), 61: ('water', None), 62: ('water', 'fighting'),
    63: ('psychic', None), 64: ('psychic', None), 65: ('psychic', None),
    66: ('fighting', None), 67: ('fighting', None), 68: ('fighting', None),
    69: ('grass', 'poison'), 70: ('grass', 'poison'), 71: ('grass', 'poison'),
    72: ('water', 'poison'), 73: ('water', 'poison'),
    74: ('rock', 'ground'), 75: ('rock', 'ground'), 76: ('rock', 'ground'),
    77: ('fire', None), 78: ('fire', None),
    79: ('water', 'psychic'), 80: ('water', 'psychic'),
    81: ('electric', 'steel'), 82: ('electric', 'steel'),  # Steel from Gen 2
    83: ('normal', 'flying'), 84: ('normal', 'flying'), 85: ('normal', 'flying'),
    86: ('water', None), 87: ('water', 'ice'),
    88: ('poison', None), 89: ('poison', None),
    90: ('water', None), 91: ('water', 'ice'),
    92: ('ghost', 'poison'), 93: ('ghost', 'poison'), 94: ('ghost', 'poison'),
    95: ('rock', 'ground'),
    96: ('psychic', None), 97: ('psychic', None),
    98: ('water', None), 99: ('water', None),
    100: ('electric', None), 101: ('electric', None),
    102: ('grass', 'psychic'), 103: ('grass', 'psychic'),
    104: ('ground', None), 105: ('ground', None),
    106: ('fighting', None), 107: ('fighting', None),
    108: ('normal', None),
    109: ('poison', None), 110: ('poison', None),
    111: ('ground', 'rock'), 112: ('ground', 'rock'),
    113: ('normal', None), 114: ('grass', None), 115: ('normal', None),
    116: ('water', None), 117: ('water', None),
    118: ('water', None), 119: ('water', None),
    120: ('water', None), 121: ('water', 'psychic'),
    122: ('psychic', 'fairy'),
    123: ('bug', 'flying'), 124: ('ice', 'psychic'),
    125: ('electric', None), 126: ('fire', None), 127: ('bug', None),
    128: ('normal', None), 129: ('water', None), 130: ('water', 'flying'),
    131: ('water', 'ice'), 132: ('normal', None), 133: ('normal', None),
    134: ('water', None), 135: ('electric', None), 136: ('fire', None),
    137: ('normal', None),
    138: ('rock', 'water'), 139: ('rock', 'water'),
    140: ('rock', 'water'), 141: ('rock', 'water'),
    142: ('rock', 'flying'), 143: ('normal', None),
    144: ('ice', 'flying'), 145: ('electric', 'flying'), 146: ('fire', 'flying'),
    147: ('dragon', None), 148: ('dragon', None), 149: ('dragon', 'flying'),
    150: ('psychic', None), 151: ('psychic', None),
    # --- generated by gen_dex_data.py
    152: ('grass', None),
    153: ('grass', None),
    154: ('grass', None),
    155: ('fire', None),
    156: ('fire', None),
    157: ('fire', None),
    158: ('water', None),
    159: ('water', None),
    160: ('water', None),
    161: ('normal', None),
    162: ('normal', None),
    163: ('normal', 'flying'),
    164: ('normal', 'flying'),
    165: ('bug', 'flying'),
    166: ('bug', 'flying'),
    167: ('bug', 'poison'),
    168: ('bug', 'poison'),
    169: ('poison', 'flying'),
    170: ('water', 'electric'),
    171: ('water', 'electric'),
    172: ('electric', None),
    173: ('fairy', None),
    174: ('normal', 'fairy'),
    175: ('fairy', None),
    176: ('fairy', 'flying'),
    177: ('psychic', 'flying'),
    178: ('psychic', 'flying'),
    179: ('electric', None),
    180: ('electric', None),
    181: ('electric', None),
    182: ('grass', None),
    183: ('water', 'fairy'),
    184: ('water', 'fairy'),
    185: ('rock', None),
    186: ('water', None),
    187: ('grass', 'flying'),
    188: ('grass', 'flying'),
    189: ('grass', 'flying'),
    190: ('normal', None),
    191: ('grass', None),
    192: ('grass', None),
    193: ('bug', 'flying'),
    194: ('water', 'ground'),
    195: ('water', 'ground'),
    196: ('psychic', None),
    197: ('dark', None),
    198: ('dark', 'flying'),
    199: ('water', 'psychic'),
    200: ('ghost', None),
    201: ('psychic', None),
    202: ('psychic', None),
    203: ('normal', 'psychic'),
    204: ('bug', None),
    205: ('bug', 'steel'),
    206: ('normal', None),
    207: ('ground', 'flying'),
    208: ('steel', 'ground'),
    209: ('fairy', None),
    210: ('fairy', None),
    211: ('water', 'poison'),
    212: ('bug', 'steel'),
    213: ('bug', 'rock'),
    214: ('bug', 'fighting'),
    215: ('dark', 'ice'),
    216: ('normal', None),
    217: ('normal', None),
    218: ('fire', None),
    219: ('fire', 'rock'),
    220: ('ice', 'ground'),
    221: ('ice', 'ground'),
    222: ('water', 'rock'),
    223: ('water', None),
    224: ('water', None),
    225: ('ice', 'flying'),
    226: ('water', 'flying'),
    227: ('steel', 'flying'),
    228: ('dark', 'fire'),
    229: ('dark', 'fire'),
    230: ('water', 'dragon'),
    231: ('ground', None),
    232: ('ground', None),
    233: ('normal', None),
    234: ('normal', None),
    235: ('normal', None),
    236: ('fighting', None),
    237: ('fighting', None),
    238: ('ice', 'psychic'),
    239: ('electric', None),
    240: ('fire', None),
    241: ('normal', None),
    242: ('normal', None),
    243: ('electric', None),
    244: ('fire', None),
    245: ('water', None),
    246: ('rock', 'ground'),
    247: ('rock', 'ground'),
    248: ('rock', 'dark'),
    249: ('psychic', 'flying'),
    250: ('fire', 'flying'),
    251: ('psychic', 'grass'),
    252: ('grass', None),
    253: ('grass', None),
    254: ('grass', None),
    255: ('fire', None),
    256: ('fire', 'fighting'),
    257: ('fire', 'fighting'),
    258: ('water', None),
    259: ('water', 'ground'),
    260: ('water', 'ground'),
    261: ('dark', None),
    262: ('dark', None),
    263: ('normal', None),
    264: ('normal', None),
    265: ('bug', None),
    266: ('bug', None),
    267: ('bug', 'flying'),
    268: ('bug', None),
    269: ('bug', 'poison'),
    270: ('water', 'grass'),
    271: ('water', 'grass'),
    272: ('water', 'grass'),
    273: ('grass', None),
    274: ('grass', 'dark'),
    275: ('grass', 'dark'),
    276: ('normal', 'flying'),
    277: ('normal', 'flying'),
    278: ('water', 'flying'),
    279: ('water', 'flying'),
    280: ('psychic', 'fairy'),
    281: ('psychic', 'fairy'),
    282: ('psychic', 'fairy'),
    283: ('bug', 'water'),
    284: ('bug', 'flying'),
    285: ('grass', None),
    286: ('grass', 'fighting'),
    287: ('normal', None),
    288: ('normal', None),
    289: ('normal', None),
    290: ('bug', 'ground'),
    291: ('bug', 'flying'),
    292: ('bug', 'ghost'),
    293: ('normal', None),
    294: ('normal', None),
    295: ('normal', None),
    296: ('fighting', None),
    297: ('fighting', None),
    298: ('normal', 'fairy'),
    299: ('rock', None),
    300: ('normal', None),
    301: ('normal', None),
    302: ('dark', 'ghost'),
    303: ('steel', 'fairy'),
    304: ('steel', 'rock'),
    305: ('steel', 'rock'),
    306: ('steel', 'rock'),
    307: ('fighting', 'psychic'),
    308: ('fighting', 'psychic'),
    309: ('electric', None),
    310: ('electric', None),
    311: ('electric', None),
    312: ('electric', None),
    313: ('bug', None),
    314: ('bug', None),
    315: ('grass', 'poison'),
    316: ('poison', None),
    317: ('poison', None),
    318: ('water', 'dark'),
    319: ('water', 'dark'),
    320: ('water', None),
    321: ('water', None),
    322: ('fire', 'ground'),
    323: ('fire', 'ground'),
    324: ('fire', None),
    325: ('psychic', None),
    326: ('psychic', None),
    327: ('normal', None),
    328: ('ground', None),
    329: ('ground', 'dragon'),
    330: ('ground', 'dragon'),
    331: ('grass', None),
    332: ('grass', 'dark'),
    333: ('normal', 'flying'),
    334: ('dragon', 'flying'),
    335: ('normal', None),
    336: ('poison', None),
    337: ('rock', 'psychic'),
    338: ('rock', 'psychic'),
    339: ('water', 'ground'),
    340: ('water', 'ground'),
    341: ('water', None),
    342: ('water', 'dark'),
    343: ('ground', 'psychic'),
    344: ('ground', 'psychic'),
    345: ('rock', 'grass'),
    346: ('rock', 'grass'),
    347: ('rock', 'bug'),
    348: ('rock', 'bug'),
    349: ('water', None),
    350: ('water', None),
    351: ('normal', None),
    352: ('normal', None),
    353: ('ghost', None),
    354: ('ghost', None),
    355: ('ghost', None),
    356: ('ghost', None),
    357: ('grass', 'flying'),
    358: ('psychic', None),
    359: ('dark', None),
    360: ('psychic', None),
    361: ('ice', None),
    362: ('ice', None),
    363: ('ice', 'water'),
    364: ('ice', 'water'),
    365: ('ice', 'water'),
    366: ('water', None),
    367: ('water', None),
    368: ('water', None),
    369: ('water', 'rock'),
    370: ('water', None),
    371: ('dragon', None),
    372: ('dragon', None),
    373: ('dragon', 'flying'),
    374: ('steel', 'psychic'),
    375: ('steel', 'psychic'),
    376: ('steel', 'psychic'),
    377: ('rock', None),
    378: ('ice', None),
    379: ('steel', None),
    380: ('dragon', 'psychic'),
    381: ('dragon', 'psychic'),
    382: ('water', None),
    383: ('ground', None),
    384: ('dragon', 'flying'),
    385: ('steel', 'psychic'),
    386: ('psychic', None),
}
