#!/usr/bin/env python3
"""Generate the compressed built-in boot splash from its source PNG."""

import os
import zlib

from gen_backs import read_png, to_indexed

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, 'assets', 'boot_splash.png')
OUT = os.path.join(HERE, '..', 'boot_splash_art.h')


def main():
    w, h, ch, rows = read_png(SRC)
    if (w, h) != (466, 466):
        raise SystemExit('boot splash must be 466x466 pixels')
    palette, indices = to_indexed(w, h, ch, rows)
    if len(palette) > 256:
        raise SystemExit('boot splash uses more than 256 RGB565 colours')
    palette.extend([0] * (256 - len(palette)))
    raw = bytes(indices)
    compressed = zlib.compress(raw, 9)
    if zlib.decompress(compressed) != raw:
        raise SystemExit('boot splash compression round-trip failed')

    out = [
        '// Generated by tools/gen_boot_splash.py from tools/assets/boot_splash.png.',
        '// Do not edit by hand.',
        '#pragma once',
        '#include <stdint.h>',
        '',
        '#define BOOT_SPLASH_WIDTH %d' % w,
        '#define BOOT_SPLASH_HEIGHT %d' % h,
        '#define BOOT_SPLASH_PIXEL_COUNT %dUL' % len(raw),
        '#define BOOT_SPLASH_PALETTE_SIZE 256',
        '#define BOOT_SPLASH_COMPRESSED_SIZE %dUL' % len(compressed),
        '',
        'static const uint16_t BOOT_SPLASH_PALETTE_RGB565[256] = {',
    ]
    for offset in range(0, len(palette), 16):
        out.append('  ' + ', '.join('0x%04X' % c
                                    for c in palette[offset:offset + 16]) + ',')
    out.extend([
        '};',
        '',
        'static const uint8_t BOOT_SPLASH_DEFLATE[BOOT_SPLASH_COMPRESSED_SIZE] = {',
    ])
    for offset in range(0, len(compressed), 24):
        out.append('  ' + ','.join(str(v)
                                  for v in compressed[offset:offset + 24]) + ',')
    out.extend(['};', ''])
    with open(OUT, 'w', encoding='utf-8') as stream:
        stream.write('\n'.join(out))
    print('boot splash: %.1f KB -> %.1f KB (%s)' %
          (len(raw) / 1024.0, len(compressed) / 1024.0,
           os.path.normpath(OUT)))


if __name__ == '__main__':
    main()
